"""Initial tables

Revision ID: 4c3a34ff25d1
Revises: 
Create Date: 2026-05-07 09:33:12.679909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c3a34ff25d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identification', sa.String(length=13), nullable=False, comment='National ID (cédula) or company tax ID (RUC)'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True, comment='MALE, FEMALE, OTHER'),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('civil_status', sa.String(length=30), nullable=True, comment='SINGLE, MARRIED, DIVORCED, WIDOWED'),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_identification'), 'customers', ['identification'], unique=True)
    op.create_table('collection_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address_line', sa.String(length=250), nullable=False, comment='Full street address including number'),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address_type', sa.String(length=30), nullable=True, comment='HOME, WORK, REFERENCE'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_addresses_customer_id'), 'collection_addresses', ['customer_id'], unique=False)
    op.create_index(op.f('ix_collection_addresses_id'), 'collection_addresses', ['id'], unique=False)
    op.create_table('collection_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=150), nullable=False, comment='Customer email address'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates whether this email address is currently active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_emails_customer_id'), 'collection_emails', ['customer_id'], unique=False)
    op.create_index(op.f('ix_collection_emails_id'), 'collection_emails', ['id'], unique=False)
    op.create_table('collection_phones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='Local phone number without country code'),
    sa.Column('country_code', sa.String(length=5), nullable=True, comment='Country dialing code, e.g. +593'),
    sa.Column('phone_type', sa.String(length=20), nullable=True, comment='MOBILE, HOME, WORK'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_phones_customer_id'), 'collection_phones', ['customer_id'], unique=False)
    op.create_index(op.f('ix_collection_phones_id'), 'collection_phones', ['id'], unique=False)
    op.create_table('equifax_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('fecha_consulta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora exacta en que se realizó la consulta al buró'),
    sa.Column('score_buro', sa.Integer(), nullable=True, comment='Score de crédito retornado por Equifax (generalmente 0 - 999)'),
    sa.Column('estado_consulta', sa.String(length=20), nullable=False, comment='Estado de la consulta: EXITOSA, FALLIDA, SIN_INFORMACION'),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Respuesta cruda (raw data) retornada por la API de Equifax en formato JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equifax_queries_customer_id'), 'equifax_queries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_equifax_queries_id'), 'equifax_queries', ['id'], unique=False)
    op.create_table('financial_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True, comment='Monthly net salary or income in USD'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_information_customer_id'), 'financial_information', ['customer_id'], unique=True)
    op.create_index(op.f('ix_financial_information_id'), 'financial_information', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_information_id'), table_name='financial_information')
    op.drop_index(op.f('ix_financial_information_customer_id'), table_name='financial_information')
    op.drop_table('financial_information')
    op.drop_index(op.f('ix_equifax_queries_id'), table_name='equifax_queries')
    op.drop_index(op.f('ix_equifax_queries_customer_id'), table_name='equifax_queries')
    op.drop_table('equifax_queries')
    op.drop_index(op.f('ix_collection_phones_id'), table_name='collection_phones')
    op.drop_index(op.f('ix_collection_phones_customer_id'), table_name='collection_phones')
    op.drop_table('collection_phones')
    op.drop_index(op.f('ix_collection_emails_id'), table_name='collection_emails')
    op.drop_index(op.f('ix_collection_emails_customer_id'), table_name='collection_emails')
    op.drop_table('collection_emails')
    op.drop_index(op.f('ix_collection_addresses_id'), table_name='collection_addresses')
    op.drop_index(op.f('ix_collection_addresses_customer_id'), table_name='collection_addresses')
    op.drop_table('collection_addresses')
    op.drop_index(op.f('ix_customers_identification'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
