"""Add economic_activity to Customer

Revision ID: 72f5922e31b9
Revises: e5f6a7b8c9d0
Create Date: 2026-06-02 20:02:03.207027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f5922e31b9'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection_addresses', 'address_line',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Full street address including number',
               existing_nullable=False)
    op.alter_column('collection_addresses', 'address_type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='HOME, WORK, REFERENCE',
               existing_nullable=True)
    op.alter_column('collection_addresses', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Origin system: Collecta, DATA SEFIL, Manual, etc.',
               existing_nullable=True)
    op.alter_column('collection_addresses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('collection_emails', 'email_address',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='Customer email address',
               existing_nullable=False)
    op.alter_column('collection_emails', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indicates whether this email address is currently active',
               existing_nullable=False)
    op.alter_column('collection_emails', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Origin system: Collecta, DATA SEFIL, Manual, etc.',
               existing_nullable=True)
    op.alter_column('collection_phones', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Local phone number without country code',
               existing_nullable=False)
    op.alter_column('collection_phones', 'country_code',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='Country dialing code, e.g. +593',
               existing_nullable=True)
    op.alter_column('collection_phones', 'phone_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='MOBILE, HOME, WORK',
               existing_nullable=True)
    op.alter_column('collection_phones', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customer_relationships', 'source',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_customer_relationships_id "
        "ON customer_relationships (id)"
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_relationships_id'), table_name='customer_relationships')
    op.alter_column('customer_relationships', 'source',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'DATA SEFIL'::character varying"),
               existing_nullable=True)
    op.alter_column('collection_phones', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('collection_phones', 'phone_type',
               existing_type=sa.VARCHAR(length=20),
               comment='MOBILE, HOME, WORK',
               existing_nullable=True)
    op.alter_column('collection_phones', 'country_code',
               existing_type=sa.VARCHAR(length=5),
               comment='Country dialing code, e.g. +593',
               existing_nullable=True)
    op.alter_column('collection_phones', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Local phone number without country code',
               existing_nullable=False)
    op.alter_column('collection_emails', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='Origin system: Collecta, DATA SEFIL, Manual, etc.',
               existing_nullable=True)
    op.alter_column('collection_emails', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Indicates whether this email address is currently active',
               existing_nullable=False)
    op.alter_column('collection_emails', 'email_address',
               existing_type=sa.VARCHAR(length=150),
               comment='Customer email address',
               existing_nullable=False)
    op.alter_column('collection_addresses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('collection_addresses', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='Origin system: Collecta, DATA SEFIL, Manual, etc.',
               existing_nullable=True)
    op.alter_column('collection_addresses', 'address_type',
               existing_type=sa.VARCHAR(length=30),
               comment='HOME, WORK, REFERENCE',
               existing_nullable=True)
    op.alter_column('collection_addresses', 'address_line',
               existing_type=sa.VARCHAR(length=500),
               comment='Full street address including number',
               existing_nullable=False)
    # ### end Alembic commands ###
