"""Add source column to collections

Revision ID: 7991cee60d14
Revises: 4c3a34ff25d1
Create Date: 2026-05-07 12:43:06.410112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7991cee60d14'
down_revision: Union[str, Sequence[str], None] = '4c3a34ff25d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_addresses', sa.Column('source', sa.String(length=50), nullable=True, comment='Origin system: Collecta, DATA SEFIL, Manual, etc.'))
    op.add_column('collection_emails', sa.Column('source', sa.String(length=50), nullable=True, comment='Origin system: Collecta, DATA SEFIL, Manual, etc.'))
    op.add_column('collection_phones', sa.Column('source', sa.String(length=50), nullable=True, comment='Origin system: Collecta, DATA SEFIL, Manual, etc.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_phones', 'source')
    op.drop_column('collection_emails', 'source')
    op.drop_column('collection_addresses', 'source')
    # ### end Alembic commands ###
