"""add_economic_activity

Revision ID: d1fd7be0d425
Revises: 72f5922e31b9
Create Date: 2026-06-08 15:20:38.811868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fd7be0d425'
down_revision: Union[str, Sequence[str], None] = '72f5922e31b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('economic_activity', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'economic_activity')
    # ### end Alembic commands ###
